import { DedicateDataFieldEnum } from "../../formValidation/enum/dedicateDataField.enum";
import { RegistrationDataSqsJsonFieldEnum } from "./RegistrationDataSqsJson.enum";

export const DictionarySqsJsonMapping = {
  [DedicateDataFieldEnum.br_email]: RegistrationDataSqsJsonFieldEnum.emailId,
  [DedicateDataFieldEnum.br_title]: RegistrationDataSqsJsonFieldEnum.title,
  [DedicateDataFieldEnum.br_first_name]: RegistrationDataSqsJsonFieldEnum.firstName,
  [DedicateDataFieldEnum.br_last_name]: RegistrationDataSqsJsonFieldEnum.lastName,
  [DedicateDataFieldEnum.br_position]: RegistrationDataSqsJsonFieldEnum.position,
  [DedicateDataFieldEnum.br_company_name]: RegistrationDataSqsJsonFieldEnum.companyName,
  [DedicateDataFieldEnum.br_address_line_1]: RegistrationDataSqsJsonFieldEnum.addressLine1,
  [DedicateDataFieldEnum.br_address_line_2]: RegistrationDataSqsJsonFieldEnum.addressLine2,
  [DedicateDataFieldEnum.br_address_line_3]: RegistrationDataSqsJsonFieldEnum.addressLine3,
  [DedicateDataFieldEnum.br_address_line_4]: RegistrationDataSqsJsonFieldEnum.addressLine4,
  [DedicateDataFieldEnum.br_address_country]: RegistrationDataSqsJsonFieldEnum.addressCountryCode,
  [DedicateDataFieldEnum.br_address_postal_code]: RegistrationDataSqsJsonFieldEnum.postalCode,
  [DedicateDataFieldEnum.br_address_state]: RegistrationDataSqsJsonFieldEnum.stateOrProvinceCode,
  [DedicateDataFieldEnum.br_address_city]: RegistrationDataSqsJsonFieldEnum.cityCode,
  [DedicateDataFieldEnum.br_country_code_company]: RegistrationDataSqsJsonFieldEnum.companyPhoneCountryCode,
  [DedicateDataFieldEnum.br_area_code_company]: RegistrationDataSqsJsonFieldEnum.companyPhoneAreaCode,
  [DedicateDataFieldEnum.br_company_number]: RegistrationDataSqsJsonFieldEnum.companyPhonePhoneNumber,
  [DedicateDataFieldEnum.br_extension_company]: RegistrationDataSqsJsonFieldEnum.companyPhoneExtension,
  [DedicateDataFieldEnum.br_mobile_number]: RegistrationDataSqsJsonFieldEnum.mobilePhoneNumber,
  [DedicateDataFieldEnum.br_country_code_mobile]: RegistrationDataSqsJsonFieldEnum.mobilePhoneCountryCode,
  [DedicateDataFieldEnum.br_company_website]: RegistrationDataSqsJsonFieldEnum.companyWebsite,
  [DedicateDataFieldEnum.br_company_background]: RegistrationDataSqsJsonFieldEnum.companyBackground,
  [DedicateDataFieldEnum.br_concent_eu_eea_clause]: RegistrationDataSqsJsonFieldEnum.euConsentStatus,
  [DedicateDataFieldEnum.br_concent_privacy_policy_statement]: RegistrationDataSqsJsonFieldEnum.badgeConsent,
  [DedicateDataFieldEnum.br_consent_registration_detail]: RegistrationDataSqsJsonFieldEnum.registrationDetailConsent,
  [DedicateDataFieldEnum.br_concent_click2match]: RegistrationDataSqsJsonFieldEnum.c2mConsent,
  [DedicateDataFieldEnum.br_business_nature]: RegistrationDataSqsJsonFieldEnum.nob,
  [DedicateDataFieldEnum.br_bm_target_supplier]: RegistrationDataSqsJsonFieldEnum.productStrategy,
  [DedicateDataFieldEnum.br_bm_prefer_supplier_country]: RegistrationDataSqsJsonFieldEnum.preferredSuppCountryRegion,
  [DedicateDataFieldEnum.br_sbe_event_list]: RegistrationDataSqsJsonFieldEnum.seminarRegistrations,
  [DedicateDataFieldEnum.br_bm_prefer_timeslot]: RegistrationDataSqsJsonFieldEnum.preferredTimeslot,
  [DedicateDataFieldEnum.br_bm_product_interest]: RegistrationDataSqsJsonFieldEnum.productInterest,
  [DedicateDataFieldEnum.br_bm_product_interest_ip]: RegistrationDataSqsJsonFieldEnum.productInterest,
  [DedicateDataFieldEnum.br_bm_product_interest_licensing]: RegistrationDataSqsJsonFieldEnum.productInterest,
}
