export enum SUBMIT_TYPE {
    VALIDATE_STEP = "VALIDATE_STEP",
    SUBMIT = "SUBMIT",
}

export enum VALIDATION_STATUS {
    STEP_PASSED = "STEP_PASSED",
    STEP_FAILED = "STEP_FAILED",
    FORM_PASSED = "FORM_PASSED",
    FORM_FAILED = "FORM_FAILED",
}

export enum LANG {
    en = "en",
    tc = "tc",
    sc = "sc",
}

export enum SUBMIT_FORM_COUNTRY {
    empty = "",
    non_china = "non_china",
    china = "china",
}

export enum FORM_SUBMISSION_STATUS {
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    FAILED_NOTIFIED = "NOTIFIED",
    REDRIVE = "REDRIVE",    
}

export const PARTICIPANT_TYPE_PRIORITY : { [key: string]: number } = {
    ORGANIC: 1,
    VIP_MISSION: 16,
    VIP_CIP: 32,
    EXHIBITOR: 64,
}

export const ELIGIBILITY_RESPONSE_CODE: {[key: string]: string} = {
    REGISTRATION_REJECTED_ACCOUNT_TEMPORARILY_RESTRICTED: 'REGISTRATION_REJECTED_ACCOUNT_TEMPORARILY_RESTRICTED',
    OUTSIDE_REGISTRATION_PERIOD: 'OUTSIDE_REGISTRATION_PERIOD',
    DISABLED_REGISTRATION: 'DISABLED_REGISTRATION',
    ELIGIBLE: 'ELIGIBLE',
    NOT_LOGGED_IN_ALREADY_REGISTERED_HAS_SSO_ACCOUNT: 'NOT_LOGGED_IN_ALREADY_REGISTERED_HAS_SSO_ACCOUNT',
    NOT_LOGGED_IN_ALREADY_REGISTERED_NO_SSO_ACCOUNT: 'NOT_LOGGED_IN_ALREADY_REGISTERED_NO_SSO_ACCOUNT',
    NOT_LOGGED_IN_EMAIL_ADDRESS_ALREADY_IN_USE: 'NOT_LOGGED_IN_EMAIL_ADDRESS_ALREADY_IN_USE',
    LOGGED_IN_ALREADY_REGISTERED_CIP: 'LOGGED_IN_ALREADY_REGISTERED_CIP',
    LOGGED_IN_ALREADY_REGISTERED_MISSION: 'LOGGED_IN_ALREADY_REGISTERED_MISSION',
    LOGGED_IN_ALREADY_REGISTERED_ORGANIC: 'LOGGED_IN_ALREADY_REGISTERED_ORGANIC',
    ALREADY_REGISTERED_EXHIBITOR: 'ALREADY_REGISTERED_EXHIBITOR',
    LOGGED_IN_LOWER_PARTICIPANT_TYPE: 'LOGGED_IN_LOWER_PARTICIPANT_TYPE'
}

export const FORM_SUBMISSION_KEY_EXPIRATION_TIME_IN_MINUTE = 60