
export enum RegFormLinkValidationErrMsg {
    VALIDATION_PASSED = "",

    DATA_LENGTH_INVALID = "DATA_LENGTH_INVALID",
    DATA_NOT_MATCH_REGEXP = "DATA_NOT_MATCH_REGEXP",
    INVALID_VISITOR_TYPE_CODE = "INVALID_VISITOR_TYPE_CODE",
}